import Image from "next/image";
import styles from "./styles.module.scss";
import "@/styles/globals.scss";
import { cn, iranYekan } from "@/lib/utils";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function EmployeeRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={cn(iranYekan.className, styles.wrapper)}>
        <nav className={styles.nav}>
          <Image
            src="/assets/logo.png"
            alt="qualia logo"
            width={146}
            height={36.5}
          />
        </nav>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
